resources:
  - ../../cert-manager
  - ../../pong
#  - ../../rhacs
#  - ../../gitlab
#  - ../../gitlab-runner
#  - ../../virtualization
#  - ../../developer-hub
#  - ../../aap
#  - ../../odf
#  - ../../keycloak