apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-permissions
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ArgoCD-permissions/aggregate/all
    repoURL: 'https://github.com/scrawley-rh/gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true